version: '3'
services:
  zipkin:
    image: qnib/plain-zipkin:2.4.0
    ports:
      - 9411:9411
  tracer:
    image: qnib/dracer:0.1.0@sha256:e3172a5000dcd619503d2f5e9d095bcea5bd517509e274df8bfe362dfdcb209e
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRACER_ZIPKIN_ENDPOINT=http://tasks.zipkin:9411/api/v1/spans
